[tasks.test]
workspace = false
command = "cargo"
args = ["test"]

[tasks.build]
workspace = false
dependencies = ["test"]
env = { RUSTFLAGS="-g"}
command = "cargo"
args = ["build" , "--release"]

[tasks.run]
desciption="usage: cargo make run"
workspace = false
dependencies = ["build"]
env = { RUSTFLAGS="-g"}
script = [
'''
tmp_data=/tmp/data
sudo cp target/release/libpgsql_ext.so /usr/lib/postgresql/12/lib/
mkdir -p $tmp_data
chmod a+rwx $tmp_data
sudo rm $tmp_data/*
psql -c "INSERT INTO table1 (my_text, my_jsonb) VALUES ('test_v3', '{}');"
sudo cat $(ls $tmp_data/*)
'''
]

[tasks.default]
dependencies = ["build"]
workspace = false

