# rm ex3.o ex3.so && make USE_PGXS=1

MODULES = ex3
EXTENSION = ex3
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

#include /usr/local/opt/postgresql@11/lib/pgxs/src/makefiles/pgxs.mk
